# Generated by Django 4.1.7 on 2023-03-05 14:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='string',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
