export const START_GAME_REQUEST = "START_GAME_REQUEST";
export const START_GAME_SUCCESS = "START_GAME_SUCCESS";
export const START_GAME_FAILED = "START_GAME_FAILED";

export const UPDATE_GAME_STRING_REQUEST = "UPDATE_GAME_STRING_REQUEST";
export const UPDATE_GAME_STRING_SUCCESS = "UPDATE_GAME_STRING_SUCCESS";
export const UPDATE_GAME_STRING_FAILED = "UPDATE_GAME_STRING_FAILED";

export const GET_GAME_STRING_REQUEST = "GET_GAME_STRING_REQUEST";
export const GET_GAME_STRING_SUCCESS = "GET_GAME_STRING_SUCCESS";
export const GET_GAME_STRING_FAILED = "GET_GAME_STRING_FAILED";
